name: flame_isometric
description: Isometric map generation using Flame, Flutter's game engine.
version: 0.1.0
homepage: https://github.com/webcyou-org/flame_isometric

environment:
  sdk: '>=2.19.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.6.0
  tiled: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/tiles/